Description: Kinesis Data Streams

#Definiendo par치metros que se usar치n dentro de la creaci칩n de recursos
Parameters: 

  pNameStream: 
    Description: Nombre de stream
    Type: String
    Default: sales-adidas

#Definiendo recursos que se crear치n en AWS
Resources:

  #Creando recurso en Kinesis Data Streams
  rStream: 
    Type: AWS::Kinesis::Stream 
    Properties: 
      Name: !Ref pNameStream
      RetentionPeriodHours: 24 #Tiempo que existen los mensajes en KDS
      ShardCount: 1
