Description: Kinesis Data Streams

Parameters: 

  pNameStream: 
    Description: Nombre de stream
    Type: String
    Default: sales-adidas

Resources:

  rStream: 
    Type: AWS::Kinesis::Stream 
    Properties: 
      Name: !Ref pNameStream
      RetentionPeriodHours: 24 #message availability time in KDS
      ShardCount: 1
